name: Execute Worlflow
on:
  push:
    branches: main

jobs:
  lint: 
    runs-on: ubuntu-latest
    steps: 
      - name: Lint code
        run: echo "Simulate linting..."
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4.2.2
      - name: Cache dependencies
        uses: actions/cache@v4.2.0
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
  build:
    if: always()
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4.2.2
      - name: Cache dependencies
        uses: actions/cache@v4.2.0
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: build-files
          path: build
  deploy:
    needs: build
    if: failure() && needs.build.outputs == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          name: build-files
      - name: Output content
        run: ls
      - name: Deploy
        run: echo "Deploying..."
  # Execute only if failed job
  report: 
    needs: [test, build, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps: 
      - name: Output infos
        run: |
          echo "Something went wrong"
          echo "${{ toJson(github) }}"