name: Handle issues
# On manually creating an issue
on: issues
jobs:
  output-info: 
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
    #   Generate issue in GitHub
        run: echo "${{ toJSON(github.event) }}"