name: React Workflow
on: push
jobs:
    buildTest:
        runs-on: ubuntu-latest
        steps:
            - name: build
              run: npm run build
            - name: test
              run: npm run test  
  